M48
; DRILL file {KiCad (6.0.2)} date Tue Aug 16 13:23:41 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-16T13:23:41+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.2)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0941
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1358
%
G90
G05
T1
X2.5197Y-4.6626
X3.3661Y-4.6626
T2
X2.5197Y-2.1614
X3.1496Y-4.3346
X3.3661Y-2.1614
X3.9961Y-4.3346
T0
M30
